project_name: goreleaser-test
builds:
  - binary: goreleaser-test
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: zip
    wrap_in_directory: true
release:
  prerelease: auto
